### ISSUE TITLE
GitHub OAuth Broken

### ISSUE THREAD

**Issue by tdaniely-dn** [reportportal/kubernetes#215]
GitHub OAuth fails with this setup.
The login request redirects to github with `redirect-uri=https://reportportal-uat.reportportal.svc.cluster.local/uat/sso/login/github&...` Which is an internal uri that is not accessible for the user.
This happens even though it receives requests with Host & X-Forwarded-Host set to the external hostname.
Need a way to tell UAT what the accessible hostname is.
Could not find the configuration in any documentation if one exists.

**Comment by tdaniely-dn** [comment]
Note same issue is also seen in reset password email & and api browser.
Reset password link in email points to internal pod name.
And in API browser the requests are sent to internal pod name & the curl copy-pasta uses internal pod name for hostname.

**Comment by HardNorth** [comment]
Double-checked, used these instructions:
https://github.com/reportportal/reportportal/wiki/How-to-configure-login-via-GitHub
https://reportportal.io/docs/GitHub-Authorization

Of course we need to update them, since both are incomplete, but it works fine with all of redirect. Note that you need to specify redirect URL in your GitHub OAuth application and not in RP.
