### ISSUE TITLE
Way to stop report portal launch when aborting Jenkins job

### ISSUE THREAD

**Issue by assiakhateeb** [reportportal/kubernetes#344]
Hi,
Is there a way to stop report portal launch when aborting Jenkins job?
Report Portal version in use is 32.2

**Issue description:**
When I abort the Jenkins job, the test results in the Report Portal keep loading in the launch section. I need to forcefully finish the suite in the Reporting Portal.
Is there a parameter or configuration to stop the Report Portal launch when aborting the Jenkins job, like a timeout parameter? Despite setting the "Launch inactivity timeout" to 1 hour, the suites still keep loading in the launch section even after 1 hour, even though the launch is finished.
Unfortunately, there is no way to stop it from the Report Portal console at least.

**Comment by Pink-Bumblebee** [comment]
**Information provided via e-mail thread.**

You can Force finish the launch from the screens of the ReportPortal like this: [https://reportportal.io/docs/work-with-reports/OperationsUnderLaunches/#force-finish-launches](https://urldefense.com/v3/__https:/reportportal.io/docs/work-with-reports/OperationsUnderLaunches/*force-finish-launches__;Iw!!GF_29dbcQIUBPA!2OmwrnKbe_odRraqHqKVrczBHQURqACqtgc_xGCWdjMCfqAZ3KwGIsyUNwm4Nnel6BZv0zFUphTFx623iadw95LwPQYCRA$)

As for the automatic finalization of the execution in case of the Jenkins Job abortion, there is no other functionality rather than “Launch Inactivity Time” and manual Force Finish.

What might make sense at this point is to have a mandatory “After step” in the Jenkins job, which will be execution even if the Job is interrupted itself, and have the API call there to force-finish the execution.
We don’t have the manual for it. But you can find the right call in the Network tab of your browser once you do a manual Force Finish on the screen on ReportPortal. And place it as a AfterStep in the Jenkins job.

Hope this helps.

 
Dmitriy Gumeniuk

**Comment by HardNorth** [comment]
@assiakhateeb Which agent do you use, BTW?
