### ISSUE TITLE
Setup "public Helm chart repository with GitHub Pages"

### ISSUE THREAD

**Issue by paulopontesm** [reportportal/kubernetes#51]
It would be nice to be able to install the report portal without having to clone the project.

For reference:
https://medium.com/@mattiaperi/create-a-public-helm-chart-repository-with-github-pages-49b180dbb417

**Comment by nbob31** [comment]
Is there any update if this will be done?

**Comment by kav** [comment]
It's worth noting this repos description for deploying the chart aren't quite how helm charts generally work. The requirements are installed as a part of the chart and requirements values are configured in the chart values, if there are required defaults, they are configured in the reportportal default values.yaml or via template since they are all generated by the same process. Requiring users to specify the service path for requirements shouldn't be needed. The names should be consistent as they are generated by the singular installation.

In general a 
```bash
helm add reportportal <url>
helm install reportportal/reportportal -n reportportal
```
should work. Happy to PR some of this if there is interest but given this issue is coming on a year and can't be PRed since it's repo config I thought perhaps I should ask first...

**Comment by patsevanton** [comment]
Hi! Thanks for reportportal!
Any news?
